name: Build and Release
on:
  push:
    tags:
      - 'v*'
env:
  BINARY_NAME: sound_lock_rust
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-gnu
          components: rustfmt, clippy
      - name: Build for Windows x86
        run: cargo build --release --target x86_64-pc-windows-gnu
      - name: Upload binaries to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-pc-windows-gnu/release/${{ env.BINARY_NAME }}.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
